name: 🐞 Bug Report
description: Let us know about a bug or crash so we can fix it.
title: "[BUG] <title>"
labels: ["bug"]

body:
  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Before you open an issue!
      description: Please keep in mind that these mods are provided for free and any support you receive is offered by volunteers. It may take a few days or even weeks to receive a response to your request. Support may be denied if you are being pushy, impatient, or demanding.
      options:
        - label: I acknowledge this and agree.
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Versions Affected
      description: "What version of Minecraft are you using? If more than one version is affected you can separate them with commas."
      placeholder: "Example: 1.16.5, 1.18.2, 1.19.2, 1.20.4"
    validations:
      required: true
  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: "What version of the mod are you using?"
      placeholder: "Example: 1.0.2"
    validations:
      required: true
  - type: dropdown
    id: mod_loader
    attributes:
      label: Mod Loaders
      description: What mod loader are you using?
      multiple: true
      options:
        - Forge
        - NeoForge
        - Fabric
        - Quilt
        - Other / Don't Know
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: "Please describe the issue you are experiencing. Any information that could help resolve the issue should also be included. For example a list of steps to recreate your issue can be very useful to narrow down and resolve your issue."
    validation:
      required: true
