name: 💥 Crash Report
description: Let us know about a crash so we can fix it!
title: "[CRASH] <title>"
labels: ["bug", "crash"]

body:
  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Before you open an issue!
      description: Please keep in mind that these mods are provided for free and any support you receive is offered by volunteers. It may take a few days or even weeks to receive a response. Support may be denied if you are being rude, impatient, or demanding.
      options:
        - label: I acknowledge this and agree.
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Versions Affected
      description: "What version of Minecraft are you using?"
      placeholder: "Example: 1.18.2"
    validations:
      required: true
  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: "What version of the mod are you using?"
      placeholder: "Example: 1.0.2"
    validations:
      required: true
  - type: dropdown
    id: mod_loader
    attributes:
      label: Mod Loaders
      description: What mod loader are you using?
      multiple: true
      options:
        - Forge
        - NeoForge
        - Fabric
        - Quilt
        - Other / Don't Know
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: "Please describe what happened leading up to the crash. For example if the game crashed after right clicking an item please mention that."
    validations:
      required: true
  - type: textarea
    id: crash_log
    attributes:
      label: Crash Log
      description: "Write or upload your crash log here. A crash log is always generated, even if you can't immediately find it."
    validations:
      required: true
