name: "⭐ Feedback"
description: "Share an idea for a new feature or change to existing content."
title: "[FEEDBACK] <title>"
labels: ["feedback"]

body:

  - type: markdown
    id: introduction
    attributes:
      value: "Thank you for taking the time to share your feedback with us. While we do appreciate your feedback please keep in mind that not all feedback can be implemented. This project is also provided for free so it may take days or even weeks to respond to your feedback."

  - type: input
    id: minecraft_version
    attributes:
      label: "Minecraft Version"
      description: "What version of Minecraft are you using?"
      placeholder: "Example: 1.18.2"
    validations:
      required: true

  - type: dropdown
    id: mod_loader
    attributes:
      label: "Mod Loader"
      description: "What mod loader are you using?"
      options:
        - "Forge"
        - "NeoForge"
        - "Fabric"
        - "Quilt"
        - "Other / Don't Know"
    validations:
      required: true

  - type: textarea
    id: feedback_description
    attributes:
      label: "Feedback"
      description: "What is your feedback for the project?"
    validations:
      required: true
